// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/reader/getreadingstate/dependencies.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/reader/getreadingstate/dependencies.go -destination=internal/usecase/reader/getreadingstate/mock_dependencies_test.go -package=getreadingstate
//

// Package getreadingstate is a generated GoMock package.
package getreadingstate

import (
	context "context"
	reflect "reflect"

	reader "github.com/deniskrylov/english-reader/backend/internal/domain/reader"
	gomock "go.uber.org/mock/gomock"
)

// MockReaderRepository is a mock of ReaderRepository interface.
type MockReaderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReaderRepositoryMockRecorder
	isgomock struct{}
}

// MockReaderRepositoryMockRecorder is the mock recorder for MockReaderRepository.
type MockReaderRepositoryMockRecorder struct {
	mock *MockReaderRepository
}

// NewMockReaderRepository creates a new mock instance.
func NewMockReaderRepository(ctrl *gomock.Controller) *MockReaderRepository {
	mock := &MockReaderRepository{ctrl: ctrl}
	mock.recorder = &MockReaderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReaderRepository) EXPECT() *MockReaderRepositoryMockRecorder {
	return m.recorder
}

// Chapter mocks base method.
func (m *MockReaderRepository) Chapter(arg0 context.Context, arg1, arg2, arg3 string) (reader.Chapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chapter", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(reader.Chapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Chapter indicates an expected call of Chapter.
func (mr *MockReaderRepositoryMockRecorder) Chapter(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chapter", reflect.TypeOf((*MockReaderRepository)(nil).Chapter), arg0, arg1, arg2, arg3)
}

// EnsureReadyBook mocks base method.
func (m *MockReaderRepository) EnsureReadyBook(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureReadyBook", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureReadyBook indicates an expected call of EnsureReadyBook.
func (mr *MockReaderRepositoryMockRecorder) EnsureReadyBook(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureReadyBook", reflect.TypeOf((*MockReaderRepository)(nil).EnsureReadyBook), arg0, arg1, arg2)
}

// FirstChapter mocks base method.
func (m *MockReaderRepository) FirstChapter(arg0 context.Context, arg1 string) (reader.Chapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstChapter", arg0, arg1)
	ret0, _ := ret[0].(reader.Chapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstChapter indicates an expected call of FirstChapter.
func (mr *MockReaderRepositoryMockRecorder) FirstChapter(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstChapter", reflect.TypeOf((*MockReaderRepository)(nil).FirstChapter), arg0, arg1)
}

// Progress mocks base method.
func (m *MockReaderRepository) Progress(arg0 context.Context, arg1, arg2 string) (reader.Progress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Progress", arg0, arg1, arg2)
	ret0, _ := ret[0].(reader.Progress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Progress indicates an expected call of Progress.
func (mr *MockReaderRepositoryMockRecorder) Progress(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Progress", reflect.TypeOf((*MockReaderRepository)(nil).Progress), arg0, arg1, arg2)
}

// Settings mocks base method.
func (m *MockReaderRepository) Settings(arg0 context.Context, arg1 string) (reader.Settings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Settings", arg0, arg1)
	ret0, _ := ret[0].(reader.Settings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Settings indicates an expected call of Settings.
func (mr *MockReaderRepositoryMockRecorder) Settings(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Settings", reflect.TypeOf((*MockReaderRepository)(nil).Settings), arg0, arg1)
}
