// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/vocabulary/saveentry/dependencies.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/vocabulary/saveentry/dependencies.go -destination=internal/usecase/vocabulary/saveentry/mock_dependencies_test.go -package=saveentry
//

// Package saveentry is a generated GoMock package.
package saveentry

import (
	context "context"
	reflect "reflect"

	vocabulary "github.com/deniskrylov/english-reader/backend/internal/domain/vocabulary"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockRepository) Save(arg0 context.Context, arg1 string, arg2 vocabulary.SaveRequest) (vocabulary.Entry, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1, arg2)
	ret0, _ := ret[0].(vocabulary.Entry)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Save indicates an expected call of Save.
func (mr *MockRepositoryMockRecorder) Save(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepository)(nil).Save), arg0, arg1, arg2)
}
