// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/dictionary/lookupword/dependencies.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/dictionary/lookupword/dependencies.go -destination=internal/usecase/dictionary/lookupword/mock_dependencies_test.go -package=lookupword
//

// Package lookupword is a generated GoMock package.
package lookupword

import (
	context "context"
	reflect "reflect"

	dictionary "github.com/deniskrylov/english-reader/backend/internal/domain/dictionary"
	gomock "go.uber.org/mock/gomock"
)

// MockWordNormalizer is a mock of WordNormalizer interface.
type MockWordNormalizer struct {
	ctrl     *gomock.Controller
	recorder *MockWordNormalizerMockRecorder
	isgomock struct{}
}

// MockWordNormalizerMockRecorder is the mock recorder for MockWordNormalizer.
type MockWordNormalizerMockRecorder struct {
	mock *MockWordNormalizer
}

// NewMockWordNormalizer creates a new mock instance.
func NewMockWordNormalizer(ctrl *gomock.Controller) *MockWordNormalizer {
	mock := &MockWordNormalizer{ctrl: ctrl}
	mock.recorder = &MockWordNormalizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWordNormalizer) EXPECT() *MockWordNormalizerMockRecorder {
	return m.recorder
}

// Normalize mocks base method.
func (m *MockWordNormalizer) Normalize(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Normalize", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Normalize indicates an expected call of Normalize.
func (mr *MockWordNormalizerMockRecorder) Normalize(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Normalize", reflect.TypeOf((*MockWordNormalizer)(nil).Normalize), arg0)
}

// MockMorphology is a mock of Morphology interface.
type MockMorphology struct {
	ctrl     *gomock.Controller
	recorder *MockMorphologyMockRecorder
	isgomock struct{}
}

// MockMorphologyMockRecorder is the mock recorder for MockMorphology.
type MockMorphologyMockRecorder struct {
	mock *MockMorphology
}

// NewMockMorphology creates a new mock instance.
func NewMockMorphology(ctrl *gomock.Controller) *MockMorphology {
	mock := &MockMorphology{ctrl: ctrl}
	mock.recorder = &MockMorphologyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMorphology) EXPECT() *MockMorphologyMockRecorder {
	return m.recorder
}

// Candidates mocks base method.
func (m *MockMorphology) Candidates(arg0 string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Candidates", arg0)
	ret0, _ := ret[0].([]string)
	return ret0
}

// Candidates indicates an expected call of Candidates.
func (mr *MockMorphologyMockRecorder) Candidates(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Candidates", reflect.TypeOf((*MockMorphology)(nil).Candidates), arg0)
}

// MockDictionaryRepository is a mock of DictionaryRepository interface.
type MockDictionaryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDictionaryRepositoryMockRecorder
	isgomock struct{}
}

// MockDictionaryRepositoryMockRecorder is the mock recorder for MockDictionaryRepository.
type MockDictionaryRepositoryMockRecorder struct {
	mock *MockDictionaryRepository
}

// NewMockDictionaryRepository creates a new mock instance.
func NewMockDictionaryRepository(ctrl *gomock.Controller) *MockDictionaryRepository {
	mock := &MockDictionaryRepository{ctrl: ctrl}
	mock.recorder = &MockDictionaryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDictionaryRepository) EXPECT() *MockDictionaryRepositoryMockRecorder {
	return m.recorder
}

// Lookup mocks base method.
func (m *MockDictionaryRepository) Lookup(arg0 context.Context, arg1 string) (dictionary.LookupResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lookup", arg0, arg1)
	ret0, _ := ret[0].(dictionary.LookupResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lookup indicates an expected call of Lookup.
func (mr *MockDictionaryRepositoryMockRecorder) Lookup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lookup", reflect.TypeOf((*MockDictionaryRepository)(nil).Lookup), arg0, arg1)
}

// MockVocabularyReader is a mock of VocabularyReader interface.
type MockVocabularyReader struct {
	ctrl     *gomock.Controller
	recorder *MockVocabularyReaderMockRecorder
	isgomock struct{}
}

// MockVocabularyReaderMockRecorder is the mock recorder for MockVocabularyReader.
type MockVocabularyReaderMockRecorder struct {
	mock *MockVocabularyReader
}

// NewMockVocabularyReader creates a new mock instance.
func NewMockVocabularyReader(ctrl *gomock.Controller) *MockVocabularyReader {
	mock := &MockVocabularyReader{ctrl: ctrl}
	mock.recorder = &MockVocabularyReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVocabularyReader) EXPECT() *MockVocabularyReaderMockRecorder {
	return m.recorder
}

// IsSaved mocks base method.
func (m *MockVocabularyReader) IsSaved(arg0 context.Context, arg1 string, arg2 int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSaved", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSaved indicates an expected call of IsSaved.
func (mr *MockVocabularyReaderMockRecorder) IsSaved(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSaved", reflect.TypeOf((*MockVocabularyReader)(nil).IsSaved), arg0, arg1, arg2)
}
