// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/dictionary/lookupword/dependencies.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/dictionary/lookupword/dependencies.go -destination=internal/usecase/dictionary/lookupword/mock_dependencies_test.go -package=lookupword
//

// Package lookupword is a generated GoMock package.
package lookupword

import (
	context "context"
	reflect "reflect"
	time "time"

	dictionary "github.com/deniskrylov/english-reader/backend/internal/domain/dictionary"
	gomock "go.uber.org/mock/gomock"
)

// MockWordNormalizer is a mock of WordNormalizer interface.
type MockWordNormalizer struct {
	ctrl     *gomock.Controller
	recorder *MockWordNormalizerMockRecorder
	isgomock struct{}
}

// MockWordNormalizerMockRecorder is the mock recorder for MockWordNormalizer.
type MockWordNormalizerMockRecorder struct {
	mock *MockWordNormalizer
}

// NewMockWordNormalizer creates a new mock instance.
func NewMockWordNormalizer(ctrl *gomock.Controller) *MockWordNormalizer {
	mock := &MockWordNormalizer{ctrl: ctrl}
	mock.recorder = &MockWordNormalizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWordNormalizer) EXPECT() *MockWordNormalizerMockRecorder {
	return m.recorder
}

// Normalize mocks base method.
func (m *MockWordNormalizer) Normalize(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Normalize", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Normalize indicates an expected call of Normalize.
func (mr *MockWordNormalizerMockRecorder) Normalize(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Normalize", reflect.TypeOf((*MockWordNormalizer)(nil).Normalize), arg0)
}

// MockMorphology is a mock of Morphology interface.
type MockMorphology struct {
	ctrl     *gomock.Controller
	recorder *MockMorphologyMockRecorder
	isgomock struct{}
}

// MockMorphologyMockRecorder is the mock recorder for MockMorphology.
type MockMorphologyMockRecorder struct {
	mock *MockMorphology
}

// NewMockMorphology creates a new mock instance.
func NewMockMorphology(ctrl *gomock.Controller) *MockMorphology {
	mock := &MockMorphology{ctrl: ctrl}
	mock.recorder = &MockMorphologyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMorphology) EXPECT() *MockMorphologyMockRecorder {
	return m.recorder
}

// Candidates mocks base method.
func (m *MockMorphology) Candidates(arg0 string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Candidates", arg0)
	ret0, _ := ret[0].([]string)
	return ret0
}

// Candidates indicates an expected call of Candidates.
func (mr *MockMorphologyMockRecorder) Candidates(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Candidates", reflect.TypeOf((*MockMorphology)(nil).Candidates), arg0)
}

// MockDictionaryRepository is a mock of DictionaryRepository interface.
type MockDictionaryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDictionaryRepositoryMockRecorder
	isgomock struct{}
}

// MockDictionaryRepositoryMockRecorder is the mock recorder for MockDictionaryRepository.
type MockDictionaryRepositoryMockRecorder struct {
	mock *MockDictionaryRepository
}

// NewMockDictionaryRepository creates a new mock instance.
func NewMockDictionaryRepository(ctrl *gomock.Controller) *MockDictionaryRepository {
	mock := &MockDictionaryRepository{ctrl: ctrl}
	mock.recorder = &MockDictionaryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDictionaryRepository) EXPECT() *MockDictionaryRepositoryMockRecorder {
	return m.recorder
}

// CachedTranslation mocks base method.
func (m *MockDictionaryRepository) CachedTranslation(arg0 context.Context, arg1, arg2 string) (dictionary.CachedTranslation, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CachedTranslation", arg0, arg1, arg2)
	ret0, _ := ret[0].(dictionary.CachedTranslation)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CachedTranslation indicates an expected call of CachedTranslation.
func (mr *MockDictionaryRepositoryMockRecorder) CachedTranslation(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CachedTranslation", reflect.TypeOf((*MockDictionaryRepository)(nil).CachedTranslation), arg0, arg1, arg2)
}

// Lookup mocks base method.
func (m *MockDictionaryRepository) Lookup(arg0 context.Context, arg1 string) (dictionary.LookupResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lookup", arg0, arg1)
	ret0, _ := ret[0].(dictionary.LookupResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lookup indicates an expected call of Lookup.
func (mr *MockDictionaryRepositoryMockRecorder) Lookup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lookup", reflect.TypeOf((*MockDictionaryRepository)(nil).Lookup), arg0, arg1)
}

// PutTranslation mocks base method.
func (m *MockDictionaryRepository) PutTranslation(arg0 context.Context, arg1, arg2, arg3 string, arg4 time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutTranslation", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutTranslation indicates an expected call of PutTranslation.
func (mr *MockDictionaryRepositoryMockRecorder) PutTranslation(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutTranslation", reflect.TypeOf((*MockDictionaryRepository)(nil).PutTranslation), arg0, arg1, arg2, arg3, arg4)
}

// MockTranslationProvider is a mock of TranslationProvider interface.
type MockTranslationProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationProviderMockRecorder
	isgomock struct{}
}

// MockTranslationProviderMockRecorder is the mock recorder for MockTranslationProvider.
type MockTranslationProviderMockRecorder struct {
	mock *MockTranslationProvider
}

// NewMockTranslationProvider creates a new mock instance.
func NewMockTranslationProvider(ctrl *gomock.Controller) *MockTranslationProvider {
	mock := &MockTranslationProvider{ctrl: ctrl}
	mock.recorder = &MockTranslationProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationProvider) EXPECT() *MockTranslationProviderMockRecorder {
	return m.recorder
}

// Translate mocks base method.
func (m *MockTranslationProvider) Translate(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Translate indicates an expected call of Translate.
func (mr *MockTranslationProviderMockRecorder) Translate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockTranslationProvider)(nil).Translate), arg0, arg1)
}

// MockReaderPort is a mock of ReaderPort interface.
type MockReaderPort struct {
	ctrl     *gomock.Controller
	recorder *MockReaderPortMockRecorder
	isgomock struct{}
}

// MockReaderPortMockRecorder is the mock recorder for MockReaderPort.
type MockReaderPortMockRecorder struct {
	mock *MockReaderPort
}

// NewMockReaderPort creates a new mock instance.
func NewMockReaderPort(ctrl *gomock.Controller) *MockReaderPort {
	mock := &MockReaderPort{ctrl: ctrl}
	mock.recorder = &MockReaderPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReaderPort) EXPECT() *MockReaderPortMockRecorder {
	return m.recorder
}

// ChapterPlainText mocks base method.
func (m *MockReaderPort) ChapterPlainText(arg0 context.Context, arg1, arg2 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChapterPlainText", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChapterPlainText indicates an expected call of ChapterPlainText.
func (mr *MockReaderPortMockRecorder) ChapterPlainText(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChapterPlainText", reflect.TypeOf((*MockReaderPort)(nil).ChapterPlainText), arg0, arg1, arg2)
}

// MockVocabularyReader is a mock of VocabularyReader interface.
type MockVocabularyReader struct {
	ctrl     *gomock.Controller
	recorder *MockVocabularyReaderMockRecorder
	isgomock struct{}
}

// MockVocabularyReaderMockRecorder is the mock recorder for MockVocabularyReader.
type MockVocabularyReaderMockRecorder struct {
	mock *MockVocabularyReader
}

// NewMockVocabularyReader creates a new mock instance.
func NewMockVocabularyReader(ctrl *gomock.Controller) *MockVocabularyReader {
	mock := &MockVocabularyReader{ctrl: ctrl}
	mock.recorder = &MockVocabularyReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVocabularyReader) EXPECT() *MockVocabularyReaderMockRecorder {
	return m.recorder
}

// IsSaved mocks base method.
func (m *MockVocabularyReader) IsSaved(arg0 context.Context, arg1 string, arg2 int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSaved", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSaved indicates an expected call of IsSaved.
func (mr *MockVocabularyReaderMockRecorder) IsSaved(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSaved", reflect.TypeOf((*MockVocabularyReader)(nil).IsSaved), arg0, arg1, arg2)
}
