// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/auth/refresh/dependencies.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/auth/refresh/dependencies.go -destination=internal/usecase/auth/refresh/mock_dependencies_test.go -package=refresh
//

// Package refresh is a generated GoMock package.
package refresh

import (
	context "context"
	reflect "reflect"
	time "time"

	auth "github.com/deniskrylov/english-reader/backend/internal/domain/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionUserFinder is a mock of SessionUserFinder interface.
type MockSessionUserFinder struct {
	ctrl     *gomock.Controller
	recorder *MockSessionUserFinderMockRecorder
	isgomock struct{}
}

// MockSessionUserFinderMockRecorder is the mock recorder for MockSessionUserFinder.
type MockSessionUserFinderMockRecorder struct {
	mock *MockSessionUserFinder
}

// NewMockSessionUserFinder creates a new mock instance.
func NewMockSessionUserFinder(ctrl *gomock.Controller) *MockSessionUserFinder {
	mock := &MockSessionUserFinder{ctrl: ctrl}
	mock.recorder = &MockSessionUserFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionUserFinder) EXPECT() *MockSessionUserFinderMockRecorder {
	return m.recorder
}

// FindUserByRefreshHash mocks base method.
func (m *MockSessionUserFinder) FindUserByRefreshHash(arg0 context.Context, arg1 []byte) (auth.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByRefreshHash", arg0, arg1)
	ret0, _ := ret[0].(auth.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByRefreshHash indicates an expected call of FindUserByRefreshHash.
func (mr *MockSessionUserFinderMockRecorder) FindUserByRefreshHash(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByRefreshHash", reflect.TypeOf((*MockSessionUserFinder)(nil).FindUserByRefreshHash), arg0, arg1)
}

// MockSessionRevoker is a mock of SessionRevoker interface.
type MockSessionRevoker struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRevokerMockRecorder
	isgomock struct{}
}

// MockSessionRevokerMockRecorder is the mock recorder for MockSessionRevoker.
type MockSessionRevokerMockRecorder struct {
	mock *MockSessionRevoker
}

// NewMockSessionRevoker creates a new mock instance.
func NewMockSessionRevoker(ctrl *gomock.Controller) *MockSessionRevoker {
	mock := &MockSessionRevoker{ctrl: ctrl}
	mock.recorder = &MockSessionRevokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRevoker) EXPECT() *MockSessionRevokerMockRecorder {
	return m.recorder
}

// RevokeSession mocks base method.
func (m *MockSessionRevoker) RevokeSession(arg0 context.Context, arg1 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSession", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSession indicates an expected call of RevokeSession.
func (mr *MockSessionRevokerMockRecorder) RevokeSession(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSession", reflect.TypeOf((*MockSessionRevoker)(nil).RevokeSession), arg0, arg1)
}

// MockSessionCreator is a mock of SessionCreator interface.
type MockSessionCreator struct {
	ctrl     *gomock.Controller
	recorder *MockSessionCreatorMockRecorder
	isgomock struct{}
}

// MockSessionCreatorMockRecorder is the mock recorder for MockSessionCreator.
type MockSessionCreatorMockRecorder struct {
	mock *MockSessionCreator
}

// NewMockSessionCreator creates a new mock instance.
func NewMockSessionCreator(ctrl *gomock.Controller) *MockSessionCreator {
	mock := &MockSessionCreator{ctrl: ctrl}
	mock.recorder = &MockSessionCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionCreator) EXPECT() *MockSessionCreatorMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockSessionCreator) CreateSession(arg0 context.Context, arg1 string, arg2 []byte, arg3 time.Time, arg4 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockSessionCreatorMockRecorder) CreateSession(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockSessionCreator)(nil).CreateSession), arg0, arg1, arg2, arg3, arg4)
}

// MockTokenIssuer is a mock of TokenIssuer interface.
type MockTokenIssuer struct {
	ctrl     *gomock.Controller
	recorder *MockTokenIssuerMockRecorder
	isgomock struct{}
}

// MockTokenIssuerMockRecorder is the mock recorder for MockTokenIssuer.
type MockTokenIssuerMockRecorder struct {
	mock *MockTokenIssuer
}

// NewMockTokenIssuer creates a new mock instance.
func NewMockTokenIssuer(ctrl *gomock.Controller) *MockTokenIssuer {
	mock := &MockTokenIssuer{ctrl: ctrl}
	mock.recorder = &MockTokenIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenIssuer) EXPECT() *MockTokenIssuerMockRecorder {
	return m.recorder
}

// Issue mocks base method.
func (m *MockTokenIssuer) Issue(arg0 string) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Issue", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Issue indicates an expected call of Issue.
func (mr *MockTokenIssuerMockRecorder) Issue(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issue", reflect.TypeOf((*MockTokenIssuer)(nil).Issue), arg0)
}

// MockRefreshTokenService is a mock of RefreshTokenService interface.
type MockRefreshTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenServiceMockRecorder
	isgomock struct{}
}

// MockRefreshTokenServiceMockRecorder is the mock recorder for MockRefreshTokenService.
type MockRefreshTokenServiceMockRecorder struct {
	mock *MockRefreshTokenService
}

// NewMockRefreshTokenService creates a new mock instance.
func NewMockRefreshTokenService(ctrl *gomock.Controller) *MockRefreshTokenService {
	mock := &MockRefreshTokenService{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenService) EXPECT() *MockRefreshTokenServiceMockRecorder {
	return m.recorder
}

// Hash mocks base method.
func (m *MockRefreshTokenService) Hash(arg0 string) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", arg0)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Hash indicates an expected call of Hash.
func (mr *MockRefreshTokenServiceMockRecorder) Hash(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockRefreshTokenService)(nil).Hash), arg0)
}

// New mocks base method.
func (m *MockRefreshTokenService) New() (string, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// New indicates an expected call of New.
func (mr *MockRefreshTokenServiceMockRecorder) New() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockRefreshTokenService)(nil).New))
}
