// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/vocabulary/gethighlights/dependencies.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/vocabulary/gethighlights/dependencies.go -destination=internal/usecase/vocabulary/gethighlights/mock_dependencies_test.go -package=gethighlights
//

// Package gethighlights is a generated GoMock package.
package gethighlights

import (
	context "context"
	reflect "reflect"

	vocabulary "github.com/deniskrylov/english-reader/backend/internal/domain/vocabulary"
	tokenizer "github.com/deniskrylov/english-reader/backend/internal/service/tokenizer"
	gomock "go.uber.org/mock/gomock"
)

// MockChapterReader is a mock of ChapterReader interface.
type MockChapterReader struct {
	ctrl     *gomock.Controller
	recorder *MockChapterReaderMockRecorder
	isgomock struct{}
}

// MockChapterReaderMockRecorder is the mock recorder for MockChapterReader.
type MockChapterReaderMockRecorder struct {
	mock *MockChapterReader
}

// NewMockChapterReader creates a new mock instance.
func NewMockChapterReader(ctrl *gomock.Controller) *MockChapterReader {
	mock := &MockChapterReader{ctrl: ctrl}
	mock.recorder = &MockChapterReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChapterReader) EXPECT() *MockChapterReaderMockRecorder {
	return m.recorder
}

// ChapterPlainText mocks base method.
func (m *MockChapterReader) ChapterPlainText(arg0 context.Context, arg1, arg2, arg3 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChapterPlainText", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChapterPlainText indicates an expected call of ChapterPlainText.
func (mr *MockChapterReaderMockRecorder) ChapterPlainText(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChapterPlainText", reflect.TypeOf((*MockChapterReader)(nil).ChapterPlainText), arg0, arg1, arg2, arg3)
}

// MockVocabularyReader is a mock of VocabularyReader interface.
type MockVocabularyReader struct {
	ctrl     *gomock.Controller
	recorder *MockVocabularyReaderMockRecorder
	isgomock struct{}
}

// MockVocabularyReaderMockRecorder is the mock recorder for MockVocabularyReader.
type MockVocabularyReaderMockRecorder struct {
	mock *MockVocabularyReader
}

// NewMockVocabularyReader creates a new mock instance.
func NewMockVocabularyReader(ctrl *gomock.Controller) *MockVocabularyReader {
	mock := &MockVocabularyReader{ctrl: ctrl}
	mock.recorder = &MockVocabularyReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVocabularyReader) EXPECT() *MockVocabularyReaderMockRecorder {
	return m.recorder
}

// HighlightLemmas mocks base method.
func (m *MockVocabularyReader) HighlightLemmas(arg0 context.Context, arg1 string, arg2 int) ([]vocabulary.HighlightLemma, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HighlightLemmas", arg0, arg1, arg2)
	ret0, _ := ret[0].([]vocabulary.HighlightLemma)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HighlightLemmas indicates an expected call of HighlightLemmas.
func (mr *MockVocabularyReaderMockRecorder) HighlightLemmas(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HighlightLemmas", reflect.TypeOf((*MockVocabularyReader)(nil).HighlightLemmas), arg0, arg1, arg2)
}

// MockTokenizer is a mock of Tokenizer interface.
type MockTokenizer struct {
	ctrl     *gomock.Controller
	recorder *MockTokenizerMockRecorder
	isgomock struct{}
}

// MockTokenizerMockRecorder is the mock recorder for MockTokenizer.
type MockTokenizerMockRecorder struct {
	mock *MockTokenizer
}

// NewMockTokenizer creates a new mock instance.
func NewMockTokenizer(ctrl *gomock.Controller) *MockTokenizer {
	mock := &MockTokenizer{ctrl: ctrl}
	mock.recorder = &MockTokenizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenizer) EXPECT() *MockTokenizerMockRecorder {
	return m.recorder
}

// Tokenize mocks base method.
func (m *MockTokenizer) Tokenize(arg0 string) ([]tokenizer.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tokenize", arg0)
	ret0, _ := ret[0].([]tokenizer.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tokenize indicates an expected call of Tokenize.
func (mr *MockTokenizerMockRecorder) Tokenize(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tokenize", reflect.TypeOf((*MockTokenizer)(nil).Tokenize), arg0)
}
