// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/reader/updatesettings/dependencies.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/reader/updatesettings/dependencies.go -destination=internal/usecase/reader/updatesettings/mock_dependencies_test.go -package=updatesettings
//

// Package updatesettings is a generated GoMock package.
package updatesettings

import (
	context "context"
	reflect "reflect"

	reader "github.com/deniskrylov/english-reader/backend/internal/domain/reader"
	gomock "go.uber.org/mock/gomock"
)

// MockSettingsRepository is a mock of SettingsRepository interface.
type MockSettingsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsRepositoryMockRecorder
	isgomock struct{}
}

// MockSettingsRepositoryMockRecorder is the mock recorder for MockSettingsRepository.
type MockSettingsRepositoryMockRecorder struct {
	mock *MockSettingsRepository
}

// NewMockSettingsRepository creates a new mock instance.
func NewMockSettingsRepository(ctrl *gomock.Controller) *MockSettingsRepository {
	mock := &MockSettingsRepository{ctrl: ctrl}
	mock.recorder = &MockSettingsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsRepository) EXPECT() *MockSettingsRepositoryMockRecorder {
	return m.recorder
}

// UpdateSettings mocks base method.
func (m *MockSettingsRepository) UpdateSettings(arg0 context.Context, arg1 string, arg2 reader.Settings) (reader.Settings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSettings", arg0, arg1, arg2)
	ret0, _ := ret[0].(reader.Settings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSettings indicates an expected call of UpdateSettings.
func (mr *MockSettingsRepositoryMockRecorder) UpdateSettings(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSettings", reflect.TypeOf((*MockSettingsRepository)(nil).UpdateSettings), arg0, arg1, arg2)
}
