// Code generated by MockGen. DO NOT EDIT.
// Source: internal/worker/epubingestion/dependencies.go
//
// Generated by this command:
//
//	mockgen -source=internal/worker/epubingestion/dependencies.go -destination=internal/worker/epubingestion/mock_dependencies_test.go -package=epubingestion
//

// Package epubingestion is a generated GoMock package.
package epubingestion

import (
	context "context"
	reflect "reflect"

	library "github.com/deniskrylov/english-reader/backend/internal/domain/library"
	epubparser "github.com/deniskrylov/english-reader/backend/internal/service/epubparser"
	gomock "go.uber.org/mock/gomock"
)

// MockJobRepository is a mock of JobRepository interface.
type MockJobRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobRepositoryMockRecorder
	isgomock struct{}
}

// MockJobRepositoryMockRecorder is the mock recorder for MockJobRepository.
type MockJobRepositoryMockRecorder struct {
	mock *MockJobRepository
}

// NewMockJobRepository creates a new mock instance.
func NewMockJobRepository(ctrl *gomock.Controller) *MockJobRepository {
	mock := &MockJobRepository{ctrl: ctrl}
	mock.recorder = &MockJobRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobRepository) EXPECT() *MockJobRepositoryMockRecorder {
	return m.recorder
}

// ClaimNextIngestion mocks base method.
func (m *MockJobRepository) ClaimNextIngestion(arg0 context.Context) (library.IngestionJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimNextIngestion", arg0)
	ret0, _ := ret[0].(library.IngestionJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimNextIngestion indicates an expected call of ClaimNextIngestion.
func (mr *MockJobRepositoryMockRecorder) ClaimNextIngestion(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimNextIngestion", reflect.TypeOf((*MockJobRepository)(nil).ClaimNextIngestion), arg0)
}

// CompleteIngestion mocks base method.
func (m *MockJobRepository) CompleteIngestion(arg0 context.Context, arg1, arg2, arg3, arg4 string, arg5 []library.Chapter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteIngestion", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteIngestion indicates an expected call of CompleteIngestion.
func (mr *MockJobRepositoryMockRecorder) CompleteIngestion(arg0, arg1, arg2, arg3, arg4, arg5 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteIngestion", reflect.TypeOf((*MockJobRepository)(nil).CompleteIngestion), arg0, arg1, arg2, arg3, arg4, arg5)
}

// FailIngestion mocks base method.
func (m *MockJobRepository) FailIngestion(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailIngestion", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailIngestion indicates an expected call of FailIngestion.
func (mr *MockJobRepositoryMockRecorder) FailIngestion(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailIngestion", reflect.TypeOf((*MockJobRepository)(nil).FailIngestion), arg0, arg1, arg2)
}

// MockCoverStorage is a mock of CoverStorage interface.
type MockCoverStorage struct {
	ctrl     *gomock.Controller
	recorder *MockCoverStorageMockRecorder
	isgomock struct{}
}

// MockCoverStorageMockRecorder is the mock recorder for MockCoverStorage.
type MockCoverStorageMockRecorder struct {
	mock *MockCoverStorage
}

// NewMockCoverStorage creates a new mock instance.
func NewMockCoverStorage(ctrl *gomock.Controller) *MockCoverStorage {
	mock := &MockCoverStorage{ctrl: ctrl}
	mock.recorder = &MockCoverStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoverStorage) EXPECT() *MockCoverStorageMockRecorder {
	return m.recorder
}

// Remove mocks base method.
func (m *MockCoverStorage) Remove(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove", arg0)
}

// Remove indicates an expected call of Remove.
func (mr *MockCoverStorageMockRecorder) Remove(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockCoverStorage)(nil).Remove), arg0)
}

// RemoveCover mocks base method.
func (m *MockCoverStorage) RemoveCover(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveCover", arg0)
}

// RemoveCover indicates an expected call of RemoveCover.
func (mr *MockCoverStorageMockRecorder) RemoveCover(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCover", reflect.TypeOf((*MockCoverStorage)(nil).RemoveCover), arg0)
}

// StoreCover mocks base method.
func (m *MockCoverStorage) StoreCover(arg0, arg1 string, arg2 []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreCover", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreCover indicates an expected call of StoreCover.
func (mr *MockCoverStorageMockRecorder) StoreCover(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreCover", reflect.TypeOf((*MockCoverStorage)(nil).StoreCover), arg0, arg1, arg2)
}

// MockEPUBParser is a mock of EPUBParser interface.
type MockEPUBParser struct {
	ctrl     *gomock.Controller
	recorder *MockEPUBParserMockRecorder
	isgomock struct{}
}

// MockEPUBParserMockRecorder is the mock recorder for MockEPUBParser.
type MockEPUBParserMockRecorder struct {
	mock *MockEPUBParser
}

// NewMockEPUBParser creates a new mock instance.
func NewMockEPUBParser(ctrl *gomock.Controller) *MockEPUBParser {
	mock := &MockEPUBParser{ctrl: ctrl}
	mock.recorder = &MockEPUBParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEPUBParser) EXPECT() *MockEPUBParserMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MockEPUBParser) Parse(arg0, arg1 string) (epubparser.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", arg0, arg1)
	ret0, _ := ret[0].(epubparser.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockEPUBParserMockRecorder) Parse(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockEPUBParser)(nil).Parse), arg0, arg1)
}
