// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/auth/logout/dependencies.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/auth/logout/dependencies.go -destination=internal/usecase/auth/logout/mock_dependencies_test.go -package=logout
//

// Package logout is a generated GoMock package.
package logout

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSessionRevoker is a mock of SessionRevoker interface.
type MockSessionRevoker struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRevokerMockRecorder
	isgomock struct{}
}

// MockSessionRevokerMockRecorder is the mock recorder for MockSessionRevoker.
type MockSessionRevokerMockRecorder struct {
	mock *MockSessionRevoker
}

// NewMockSessionRevoker creates a new mock instance.
func NewMockSessionRevoker(ctrl *gomock.Controller) *MockSessionRevoker {
	mock := &MockSessionRevoker{ctrl: ctrl}
	mock.recorder = &MockSessionRevokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRevoker) EXPECT() *MockSessionRevokerMockRecorder {
	return m.recorder
}

// RevokeSession mocks base method.
func (m *MockSessionRevoker) RevokeSession(arg0 context.Context, arg1 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSession", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSession indicates an expected call of RevokeSession.
func (mr *MockSessionRevokerMockRecorder) RevokeSession(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSession", reflect.TypeOf((*MockSessionRevoker)(nil).RevokeSession), arg0, arg1)
}

// MockRefreshTokenHasher is a mock of RefreshTokenHasher interface.
type MockRefreshTokenHasher struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenHasherMockRecorder
	isgomock struct{}
}

// MockRefreshTokenHasherMockRecorder is the mock recorder for MockRefreshTokenHasher.
type MockRefreshTokenHasherMockRecorder struct {
	mock *MockRefreshTokenHasher
}

// NewMockRefreshTokenHasher creates a new mock instance.
func NewMockRefreshTokenHasher(ctrl *gomock.Controller) *MockRefreshTokenHasher {
	mock := &MockRefreshTokenHasher{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenHasher) EXPECT() *MockRefreshTokenHasherMockRecorder {
	return m.recorder
}

// Hash mocks base method.
func (m *MockRefreshTokenHasher) Hash(arg0 string) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", arg0)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Hash indicates an expected call of Hash.
func (mr *MockRefreshTokenHasherMockRecorder) Hash(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockRefreshTokenHasher)(nil).Hash), arg0)
}
