// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/dictionary/translatetext/dependencies.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/dictionary/translatetext/dependencies.go -destination=internal/usecase/dictionary/translatetext/mock_dependencies_test.go -package=translatetext
//

// Package translatetext is a generated GoMock package.
package translatetext

import (
	context "context"
	reflect "reflect"
	time "time"

	dictionary "github.com/deniskrylov/english-reader/backend/internal/domain/dictionary"
	gomock "go.uber.org/mock/gomock"
)

// MockTranslationCache is a mock of TranslationCache interface.
type MockTranslationCache struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationCacheMockRecorder
	isgomock struct{}
}

// MockTranslationCacheMockRecorder is the mock recorder for MockTranslationCache.
type MockTranslationCacheMockRecorder struct {
	mock *MockTranslationCache
}

// NewMockTranslationCache creates a new mock instance.
func NewMockTranslationCache(ctrl *gomock.Controller) *MockTranslationCache {
	mock := &MockTranslationCache{ctrl: ctrl}
	mock.recorder = &MockTranslationCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationCache) EXPECT() *MockTranslationCacheMockRecorder {
	return m.recorder
}

// CachedTranslation mocks base method.
func (m *MockTranslationCache) CachedTranslation(arg0 context.Context, arg1, arg2 string) (dictionary.CachedTranslation, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CachedTranslation", arg0, arg1, arg2)
	ret0, _ := ret[0].(dictionary.CachedTranslation)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CachedTranslation indicates an expected call of CachedTranslation.
func (mr *MockTranslationCacheMockRecorder) CachedTranslation(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CachedTranslation", reflect.TypeOf((*MockTranslationCache)(nil).CachedTranslation), arg0, arg1, arg2)
}

// PutTranslation mocks base method.
func (m *MockTranslationCache) PutTranslation(arg0 context.Context, arg1, arg2, arg3 string, arg4 time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutTranslation", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutTranslation indicates an expected call of PutTranslation.
func (mr *MockTranslationCacheMockRecorder) PutTranslation(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutTranslation", reflect.TypeOf((*MockTranslationCache)(nil).PutTranslation), arg0, arg1, arg2, arg3, arg4)
}

// MockTranslationProvider is a mock of TranslationProvider interface.
type MockTranslationProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationProviderMockRecorder
	isgomock struct{}
}

// MockTranslationProviderMockRecorder is the mock recorder for MockTranslationProvider.
type MockTranslationProviderMockRecorder struct {
	mock *MockTranslationProvider
}

// NewMockTranslationProvider creates a new mock instance.
func NewMockTranslationProvider(ctrl *gomock.Controller) *MockTranslationProvider {
	mock := &MockTranslationProvider{ctrl: ctrl}
	mock.recorder = &MockTranslationProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationProvider) EXPECT() *MockTranslationProviderMockRecorder {
	return m.recorder
}

// Translate mocks base method.
func (m *MockTranslationProvider) Translate(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Translate indicates an expected call of Translate.
func (mr *MockTranslationProviderMockRecorder) Translate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockTranslationProvider)(nil).Translate), arg0, arg1)
}

// MockReaderPort is a mock of ReaderPort interface.
type MockReaderPort struct {
	ctrl     *gomock.Controller
	recorder *MockReaderPortMockRecorder
	isgomock struct{}
}

// MockReaderPortMockRecorder is the mock recorder for MockReaderPort.
type MockReaderPortMockRecorder struct {
	mock *MockReaderPort
}

// NewMockReaderPort creates a new mock instance.
func NewMockReaderPort(ctrl *gomock.Controller) *MockReaderPort {
	mock := &MockReaderPort{ctrl: ctrl}
	mock.recorder = &MockReaderPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReaderPort) EXPECT() *MockReaderPortMockRecorder {
	return m.recorder
}

// ChapterPlainText mocks base method.
func (m *MockReaderPort) ChapterPlainText(arg0 context.Context, arg1, arg2 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChapterPlainText", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChapterPlainText indicates an expected call of ChapterPlainText.
func (mr *MockReaderPortMockRecorder) ChapterPlainText(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChapterPlainText", reflect.TypeOf((*MockReaderPort)(nil).ChapterPlainText), arg0, arg1, arg2)
}
