// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/vocabulary/listentries/dependencies.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/vocabulary/listentries/dependencies.go -destination=internal/usecase/vocabulary/listentries/mock_dependencies_test.go -package=listentries
//

// Package listentries is a generated GoMock package.
package listentries

import (
	context "context"
	reflect "reflect"

	vocabulary "github.com/deniskrylov/english-reader/backend/internal/domain/vocabulary"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockRepository) List(arg0 context.Context, arg1 string, arg2 vocabulary.ListRequest) ([]vocabulary.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].([]vocabulary.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), arg0, arg1, arg2)
}

// MockWordNormalizer is a mock of WordNormalizer interface.
type MockWordNormalizer struct {
	ctrl     *gomock.Controller
	recorder *MockWordNormalizerMockRecorder
	isgomock struct{}
}

// MockWordNormalizerMockRecorder is the mock recorder for MockWordNormalizer.
type MockWordNormalizerMockRecorder struct {
	mock *MockWordNormalizer
}

// NewMockWordNormalizer creates a new mock instance.
func NewMockWordNormalizer(ctrl *gomock.Controller) *MockWordNormalizer {
	mock := &MockWordNormalizer{ctrl: ctrl}
	mock.recorder = &MockWordNormalizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWordNormalizer) EXPECT() *MockWordNormalizerMockRecorder {
	return m.recorder
}

// Normalize mocks base method.
func (m *MockWordNormalizer) Normalize(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Normalize", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Normalize indicates an expected call of Normalize.
func (mr *MockWordNormalizerMockRecorder) Normalize(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Normalize", reflect.TypeOf((*MockWordNormalizer)(nil).Normalize), arg0)
}
