// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/grpc/auth/login/dependencies.go
//
// Generated by this command:
//
//	mockgen -source=internal/handler/grpc/auth/login/dependencies.go -destination=internal/handler/grpc/auth/login/mock_dependencies_test.go -package=login
//

// Package login is a generated GoMock package.
package login

import (
	context "context"
	reflect "reflect"

	auth "github.com/deniskrylov/english-reader/backend/internal/domain/auth"
	login "github.com/deniskrylov/english-reader/backend/internal/usecase/auth/login"
	gomock "go.uber.org/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
	isgomock struct{}
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUseCase) Execute(arg0 context.Context, arg1 login.Request) (auth.Tokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(auth.Tokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockUseCaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUseCase)(nil).Execute), arg0, arg1)
}
