// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/vocabulary/deleteentry/dependencies.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/vocabulary/deleteentry/dependencies.go -destination=internal/usecase/vocabulary/deleteentry/mock_dependencies_test.go -package=deleteentry
//

// Package deleteentry is a generated GoMock package.
package deleteentry

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockRepository) DeleteByID(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockRepositoryMockRecorder) DeleteByID(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockRepository)(nil).DeleteByID), arg0, arg1, arg2)
}

// DeleteByLemmaID mocks base method.
func (m *MockRepository) DeleteByLemmaID(arg0 context.Context, arg1 string, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByLemmaID", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByLemmaID indicates an expected call of DeleteByLemmaID.
func (mr *MockRepositoryMockRecorder) DeleteByLemmaID(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByLemmaID", reflect.TypeOf((*MockRepository)(nil).DeleteByLemmaID), arg0, arg1, arg2)
}
