// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/auth/getme/dependencies.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/auth/getme/dependencies.go -destination=internal/usecase/auth/getme/mock_dependencies_test.go -package=getme
//

// Package getme is a generated GoMock package.
package getme

import (
	context "context"
	reflect "reflect"

	auth "github.com/deniskrylov/english-reader/backend/internal/domain/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockAccessTokenParser is a mock of AccessTokenParser interface.
type MockAccessTokenParser struct {
	ctrl     *gomock.Controller
	recorder *MockAccessTokenParserMockRecorder
	isgomock struct{}
}

// MockAccessTokenParserMockRecorder is the mock recorder for MockAccessTokenParser.
type MockAccessTokenParserMockRecorder struct {
	mock *MockAccessTokenParser
}

// NewMockAccessTokenParser creates a new mock instance.
func NewMockAccessTokenParser(ctrl *gomock.Controller) *MockAccessTokenParser {
	mock := &MockAccessTokenParser{ctrl: ctrl}
	mock.recorder = &MockAccessTokenParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessTokenParser) EXPECT() *MockAccessTokenParserMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MockAccessTokenParser) Parse(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockAccessTokenParserMockRecorder) Parse(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockAccessTokenParser)(nil).Parse), arg0)
}

// MockUserFinder is a mock of UserFinder interface.
type MockUserFinder struct {
	ctrl     *gomock.Controller
	recorder *MockUserFinderMockRecorder
	isgomock struct{}
}

// MockUserFinderMockRecorder is the mock recorder for MockUserFinder.
type MockUserFinderMockRecorder struct {
	mock *MockUserFinder
}

// NewMockUserFinder creates a new mock instance.
func NewMockUserFinder(ctrl *gomock.Controller) *MockUserFinder {
	mock := &MockUserFinder{ctrl: ctrl}
	mock.recorder = &MockUserFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserFinder) EXPECT() *MockUserFinderMockRecorder {
	return m.recorder
}

// FindUserByID mocks base method.
func (m *MockUserFinder) FindUserByID(arg0 context.Context, arg1 string) (auth.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByID", arg0, arg1)
	ret0, _ := ret[0].(auth.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByID indicates an expected call of FindUserByID.
func (mr *MockUserFinderMockRecorder) FindUserByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByID", reflect.TypeOf((*MockUserFinder)(nil).FindUserByID), arg0, arg1)
}
