// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/reader/getsettings/dependencies.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/reader/getsettings/dependencies.go -destination=internal/usecase/reader/getsettings/mock_dependencies_test.go -package=getsettings
//

// Package getsettings is a generated GoMock package.
package getsettings

import (
	context "context"
	reflect "reflect"

	reader "github.com/deniskrylov/english-reader/backend/internal/domain/reader"
	gomock "go.uber.org/mock/gomock"
)

// MockSettingsRepository is a mock of SettingsRepository interface.
type MockSettingsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsRepositoryMockRecorder
	isgomock struct{}
}

// MockSettingsRepositoryMockRecorder is the mock recorder for MockSettingsRepository.
type MockSettingsRepositoryMockRecorder struct {
	mock *MockSettingsRepository
}

// NewMockSettingsRepository creates a new mock instance.
func NewMockSettingsRepository(ctrl *gomock.Controller) *MockSettingsRepository {
	mock := &MockSettingsRepository{ctrl: ctrl}
	mock.recorder = &MockSettingsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsRepository) EXPECT() *MockSettingsRepositoryMockRecorder {
	return m.recorder
}

// Settings mocks base method.
func (m *MockSettingsRepository) Settings(arg0 context.Context, arg1 string) (reader.Settings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Settings", arg0, arg1)
	ret0, _ := ret[0].(reader.Settings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Settings indicates an expected call of Settings.
func (mr *MockSettingsRepositoryMockRecorder) Settings(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Settings", reflect.TypeOf((*MockSettingsRepository)(nil).Settings), arg0, arg1)
}
